# Logging configuration. Valid options are: LOG_ERROR, LOG_WARNING, LOG_INFO, LOG_DEBUG, LOG_TRACE
logLevel: LOG_ERROR

# Hostname of the coordinator, to which the worker should register upon startup.
# Corresponds to the service name in docker-compose.yml.
coordinatorHost: coordinator

# Hostname under which this worker registers with the coordinator. Corresponds to the service name in docker-compose.yml.
localWorkerHost: consumers-worker-1

# Physical source configuration
physicalSources:
  - logicalSourceName: consumers
    physicalSourceName: streetLights
    type: MQTT_SOURCE
    configuration:
      url: ws://mosquitto:9001
      topic: streetLights

workerId: 2