# Logging configuration. Valid options are: LOG_ERROR, LOG_WARNING, LOG_INFO, LOG_DEBUG, LOG_TRACE
logLevel: LOG_ERROR

# Hostname of the coordinator, to which the worker should register upon startup.
# Corresponds to the service name in docker-compose.yml.
coordinatorHost: coordinator

# Hostname under which this worker registers with the coordinator. Corresponds to the service name in docker-compose.yml.
localWorkerHost: producers-worker

# Physical source configuration
physicalSources:
  - logicalSourceName: solarPanels
    physicalSourceName: solarPanels
    type: MQTT_SOURCE
    configuration:
      url: ws://mosquitto:9001
      topic: solarPanels
      clientId: NES_source_solarPanels_
      userName: solarPanels
      qos: 0
      inputFormat: JSON
      cleanSession: true
      flushIntervalMS: 60
  - logicalSourceName: windTurbines
    physicalSourceName: windTurbines
    type: MQTT_SOURCE
    configuration:
      url: ws://mosquitto:9001
      topic: windTurbines
      clientId: NES_source_windTurbines_
      userName: windTurbines
      qos: 0
      inputFormat: JSON
      cleanSession: true
      flushIntervalMS: 60

workerId: 3
