# Logging configuration. Valid options are: LOG_ERROR, LOG_WARNING, LOG_INFO, LOG_DEBUG, LOG_TRACE
logLevel: LOG_ERROR

# Hostname of the coordinator, to which the worker should register upon startup.
# Corresponds to the service name in docker-compose.yml.
coordinatorHost: coordinator

# Hostname under which this worker registers with the coordinator. Corresponds to the service name in docker-compose.yml.
localWorkerHost: windturbine-worker

# Physical source configuration
physicalSources:
  - logicalSourceName: windTurbines
    physicalSourceName: windTurbines
    type: MQTT_SOURCE
    configuration:
      url: ws://mosquitto:9001
      topic: windTurbines

workerId: 5