# Automatically provision the NebulaStream tutorial dashboard.
#
# Documentation:
# - https://grafana.com/docs/grafana/latest/administration/provisioning/
# - https://grafana.com/grafana/plugins/grafana-mqtt-datasource/
#
# Unfortunately, the URI to the MQTT server is not picked up automatically.
# Before the dashboard can be first used, it has to be configured manually.
# See: https://community.grafana.com/t/unable-to-set-mqtt-broker-uri-when-provisioning-mqtt-datasource-in-docker-container/124033

apiVersion: 1

datasources:
  - name: 'NES_datatown'
    type: 'grafana-mqtt-datasource'
    isDefault: true
    editable: true
    version: 1
    "jsonData": {
      "uri": "ws://mosquitto:9001"
    }
